import type { Selector } from '../core/types.js';
import type { Clause, NormalizedConfig, NormalizedRule } from '../config/model.js';

/** Wrap each value in backticks and join with `, ` (e.g. ``a``, ``b``). */
function code(values: readonly string[]): string {
  return values.map((v) => `\`${v}\``).join(', ');
}

function humanNotHave(v: 'defaultExport' | 'namespaceExport'): string {
  return v === 'defaultExport' ? 'default exports' : 'namespace exports';
}

/** Render a rule/expectation selector as plain text. */
export function describeSelector(selector: Selector): string {
  if (selector.kind === 'layer') return `the \`${selector.layer}\` layer`;
  return `files matching ${code(selector.patterns)}`;
}

/** Render a single expectation clause as a plain-language sentence. */
export function describeClause(clause: Clause): string {
  switch (clause.kind) {
    case 'be':
      return `must be a ${code(clause.values)}`;
    case 'extend':
      return `must extend one of: ${code(clause.values)}`;
    case 'implement':
      return `must implement: ${code(clause.values)}`;
    case 'haveMethod':
      return `must declare method(s): ${code(clause.values)}`;
    case 'haveDecorator':
      return `must be decorated with: ${code(clause.values)}`;
    case 'notHaveDecorator':
      return `must not be decorated with: ${code(clause.values)}`;
    case 'notCall':
      return `must not call: ${code(clause.values)}`;
    case 'notInstantiate':
      return `must not instantiate: ${code(clause.values)}`;
    case 'haveSuffix':
      return `name must end with: ${code(clause.values)}`;
    case 'notHave':
      return `must not use: ${clause.values.map(humanNotHave).join(', ')}`;
    case 'export':
      return 'must use named exports only (no default or namespace exports)';
    case 'onlyBeUsedIn':
      return `may only be imported from: ${code(clause.values)}`;
    case 'notBeUsedIn':
      return `must not be imported from: ${code(clause.values)}`;
    case 'notDependOnPackages':
      return `must not depend on npm packages: ${code(clause.values)}`;
    case 'notDependOnPaths':
      return `must not depend on paths: ${code(clause.values)}`;
  }
}

/** Render a dependency-graph rule as a plain-language sentence. */
export function describeRule(rule: NormalizedRule): string {
  switch (rule.type) {
    case 'no-cycles': {
      const unit =
        rule.scope === 'layer' ? 'layers' : rule.scope === 'module' ? 'modules' : 'files';
      return `No dependency cycles between ${unit}.`;
    }
    case 'forbidden-import': {
      const exceptions: string[] = [];
      if (rule.except.sameModule) exceptions.push('allowed within the same module');
      if (rule.except.publicApi.length > 0) {
        exceptions.push(`except the public API: ${code(rule.except.publicApi)}`);
      }
      const tail = exceptions.length > 0 ? ` (${exceptions.join('; ')})` : '';
      return `${describeSelector(rule.from)} must not import ${describeSelector(rule.to)}.${tail}`;
    }
    case 'allowed-dependency':
      return `${describeSelector(rule.from)} may only depend on ${describeSelector(rule.allow)}.`;
    case 'public-api-boundary':
      return `a module may only be imported through its public API${
        rule.except.sameModule ? ' (except within the same module)' : ''
      }.`;
  }
}

/** Whether any expectation mandates named exports (drives the checklist hint). */
function requiresNamedExports(config: NormalizedConfig): boolean {
  return config.expectations.some((e) =>
    e.clauses.some((c) => c.kind === 'export' || (c.kind === 'notHave' && c.values.length > 0)),
  );
}

/**
 * Build a deterministic, human/AI-readable description of the project's
 * architecture rules from the normalized config. Pure (no I/O, no clock); the
 * resulting markdown is the body of the managed agent-docs block.
 */
export function buildArchitectureGuide(config: NormalizedConfig): string {
  const configFile = config.sourcePath.split('/').pop() ?? 'arch-contract.yaml';
  const lines: string[] = [
    `## Architecture Rules (${config.project.name})`,
    '',
    `> Generated by ArchContract from \`${configFile}\`. Do not edit between the markers — ` +
      'run `arch-contract sync-agent-rules` to regenerate. Generated code MUST follow these ' +
      `rules; \`${config.agent.validationCommand}\` will fail on any violation.`,
  ];

  if (config.layers.length > 0) {
    lines.push('', '### Layers — where code lives');
    lines.push('Every source file belongs to exactly one layer, decided by its path:');
    for (const layer of config.layers) {
      lines.push(`- **${layer.name}** — ${code(layer.match)}`);
    }
  }

  const rulesetEntries = Object.entries(config.ruleset);
  if (rulesetEntries.length > 0) {
    lines.push('', '### Allowed dependencies');
    lines.push(
      'A layer may import only from the layers listed below (and itself); anything else fails.',
    );
    for (const [layer, { mayDependOn }] of rulesetEntries) {
      lines.push(
        mayDependOn.length > 0
          ? `- **${layer}** may depend on: ${code(mayDependOn)}.`
          : `- **${layer}** may not depend on any other layer.`,
      );
    }
  }

  lines.push('', '### Module boundaries');
  lines.push(
    `- Modules live at \`${config.modules.pattern}\`. Import across modules only through the ` +
      `module's public API file \`${config.modules.publicApi}\` — never reach into a module's internals.`,
  );

  if (config.rules.length > 0) {
    lines.push('', '### Import rules');
    for (const rule of config.rules) {
      lines.push(`- **${rule.name}**: ${describeRule(rule)}`);
    }
  }

  if (config.expectations.length > 0) {
    lines.push('', '### Naming & code conventions');
    for (const exp of config.expectations) {
      const applies = exp.appliesTo ? `, applies to: ${exp.appliesTo.kind.join(', ')}` : '';
      lines.push(`- **${exp.name}** — ${describeSelector(exp.selector)}${applies}:`);
      for (const clause of exp.clauses) {
        lines.push(`  - ${describeClause(clause)}`);
      }
    }
  }

  lines.push('', '### Adding a new file — checklist');
  lines.push('1. Pick the layer it belongs to and put it under that layer\'s path (see "Layers").');
  lines.push(
    '2. Follow the naming convention for that layer (suffixes from "Naming & code conventions").',
  );
  lines.push('3. Only import from layers this layer may depend on (see "Allowed dependencies").');
  lines.push(`4. Cross-module imports go through \`${config.modules.publicApi}\` only.`);
  if (requiresNamedExports(config)) {
    lines.push('5. Use named exports (no default/namespace exports).');
  }

  lines.push('', '### Before you finish');
  lines.push(`Run \`${config.agent.validationCommand}\` and fix every violation in code.`);
  lines.push('Do not weaken or delete rules to make it pass.');

  return lines.join('\n');
}
